   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.4 (r3375) - 10 Feb 2010 15:08
   !
   !      ==================================================================
   MODULE INPUTOVERSET_SPATIAL_D
   USE PRECISION
   IMPLICIT NONE
   !
   !      ******************************************************************
   !      *                                                                *
   !      * Input parameters which are related to verset grid assembly and *
   !      * interpolation procedures.                                      *
   !      *                                                                *
   !      ******************************************************************
   !
   SAVE 
   !
   !      ******************************************************************
   !      *                                                                *
   !      * Definition of some parameters which make the code more         *
   !      * readable. The actual values of this parameters are arbitrary;  *
   !      * in the code always the symbolic names are (should be) used.    *
   !      *                                                                *
   !      ******************************************************************
   !
   INTEGER(kind=inttype), PARAMETER :: trilinear=1_intType
   INTEGER(kind=inttype), DIMENSION(1), PARAMETER :: ndonorweights=(/8/)
   !
   !      ******************************************************************
   !      *                                                                *
   !      * Definition of the overset input parameters.                    *
   !      *                                                                *
   !      ******************************************************************
   !
   ! oversetDonorsAreGuesses: Whether or not the input overset donors
   !                          should be treated as guesses, which
   !                          causes the interpolants to be ignored
   !                          and are determined automatically.
   ! avgRestrictResforBlanks: Whether or not to amplify or average
   !                          the restricted residual in multigrid
   !                          to account for the fact that a coarse
   !                          unblanked cell may contain blanked
   !                          cells on the next finer level.
   ! oversetInterpType:       Type of interpolation to use on the
   !                          fine grid level.
   ! oversetInterpTypeCoarse: Idem for the coarse levels.
   ! allowableDonorQuality:   The cut-off value for the quality of
   !                          a donor stencil when searches are
   !                          performed.
   LOGICAL :: oversetdonorsareguesses, avgrestrictresforblanks
   INTEGER(kind=inttype) :: oversetinterptype
   INTEGER(kind=inttype) :: oversetinterptypecoarse
   REAL(kind=realtype) :: allowabledonorquality
   END MODULE INPUTOVERSET_SPATIAL_D
