   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.4 (r3375) - 10 Feb 2010 15:08
   !
   MODULE INPUTTSSTABDERIV_SPATIAL_D
   IMPLICIT NONE
   !
   !      ******************************************************************
   !      *                                                                *
   !      * Definition of some parameters for Time Spectral stability      *
   !      * derivatives.                                                   *
   !      * The actual values of this parameters are arbitrary;            *
   !      * in the code always the symbolic names are (should be) used.    *
   !      *                                                                *
   !      *******************************************m***********************
   !
   ! TSStability : Whether or not the TS stability derivatives should
   !               be computed
   LOGICAL :: tsstability, tsalphamode, tsbetamode, tspmode, tsqmode, &
   &  tsrmode, tsaltitudemode, tsmachmode
   ! useWindAxis : whether to rotate around the wind axis or the body
   !               axis...
   LOGICAL :: usewindaxis
   END MODULE INPUTTSSTABDERIV_SPATIAL_D
