   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.4 (r3375) - 10 Feb 2010 15:08
   !
   !
   !      ******************************************************************
   !      *                                                                *
   !      * File:          su_mpi.F90                                     *
   !      * Author:        Edwin van der Weide                             *
   !      * Starting date: 12-11-2003                                      *
   !      * Last modified: 10-28-2005                                      *
   !      *                                                                *
   !      ******************************************************************
   !
   MODULE SU_MPI_SPATIAL_D
   IMPLICIT NONE
   !=================================================================
   !       contains
   !===============================================================
   !          double precision function MPI_Wtime()
   ! !
   ! !        ****************************************************************
   ! !        *                                                              *
   ! !        * The subroutine MPI_Wtime returns the elapsed wall-clock time *
   ! !        * in seconds since some time in the past. A C-function is      *
   ! !        * called to do the actual work.                                *
   ! !        *                                                              *
   ! !        ****************************************************************
   ! !
   !          implicit none
   ! !
   ! !        ****************************************************************
   ! !        *                                                              *
   ! !        * Begin execution                                              *
   ! !        *                                                              *
   ! !        ****************************************************************
   ! !
   !          double precision :: my_time
   !          MPI_Wtime = my_time()
   !          end function MPI_Wtime
   !!##else
   !!$!
   !!$!      ******************************************************************
   !!$!      *                                                                *
   !!$!      * Part that is used in parallel mode.                            *
   !!$!      *                                                                *
   !!$!      ******************************************************************
   !!$!
   !!$       ! Either load the include file or the module.
   !!$
   !!$!!## ifdef USE_MPI_INCLUDE_FILE
   !!$       implicit none
   !!$       include "mpif.h"
   !!$!!## else
   !!$       use mpi
   !!$       implicit none
   !!$!!## endif
   !!$
   !!$       ! Parameter to indicate that a parallel code is built.
   !!$
   !!$       logical, parameter :: SU_MPI_isSequential = .false.
   !!$
   !!$       ! Some definitions depending whether or not parallel IO
   !!$       ! is supported.
   !!$
   !!$!!##  ifdef USE_NO_MPIO
   !!$
   !!$       ! Parameter to indicate that parallel IO via MPIO is no
   !!$       ! supported.
   !!$
   !!$       logical, parameter :: SU_MPI_noMPIO = .true.
   !!$
   !!$       ! The corresponding MPI IO parameters must be defined.
   !!$       ! Otherwise SUmb will not compile.
   !!$
   !!$       integer, parameter :: mpi_mode_rdonly          =   2
   !!$       integer, parameter :: mpi_mode_rdwr            =   8
   !!$       integer, parameter :: mpi_mode_wronly          =   4
   !!$       integer, parameter :: mpi_mode_create          =   1
   !!$       integer, parameter :: mpi_mode_delete_on_close =  16
   !!$       integer, parameter :: mpi_mode_unique_open     =  32
   !!$       integer, parameter :: mpi_mode_excl            =  64
   !!$       integer, parameter :: mpi_mode_append          = 128
   !!$       integer, parameter :: mpi_mode_sequential      = 256
   !!$
   !!$       integer, parameter :: mpi_file_null          =   0
   !!$       integer, parameter :: mpi_max_datarep_string = 128
   !!$
   !!$       integer, parameter :: mpi_seek_set = 600
   !!$       integer, parameter :: mpi_seek_cur = 602
   !!$       integer, parameter :: mpi_seek_end = 604
   !!$
   !!$       integer, parameter :: mpio_request_null = 0
   !!$
   !!$       integer(kind=8), parameter :: mpi_displacement_current = -54278278
   !!$
   !!$       integer, parameter :: mpi_order_c       = 56
   !!$       integer, parameter :: mpi_order_fortran = 57
   !!$
   !!$       integer, parameter :: mpi_distribute_block     =    121
   !!$       integer, parameter :: mpi_distribute_cyclic    =    122
   !!$       integer, parameter :: mpi_distribute_none      =    123
   !!$       integer, parameter :: mpi_distribute_dflt_darg = -49767
   !!$
   !!##  else
   !!$
   !!$       ! Parameter to indicate that parallel IO via MPIO is supported.
   !!$
   !!$       logical, parameter :: SU_MPI_noMPIO = .false.
   !!$
   !!##  endif
   !!$
   !!$!!##endif
   SAVE 
   ! Parameter to indicate that a sequential code is built.
   LOGICAL, PARAMETER :: su_mpi_issequential=.true.
   ! Parameter to indicate that parallel IO is faked. This parameter
   ! needs to be defined to avoid compiler errors. Its value does
   ! not matter.
   LOGICAL, PARAMETER :: su_mpi_nompio=.false.
   ! mpi_status
   INTEGER, PARAMETER :: mpi_source=1
   INTEGER, PARAMETER :: mpi_tag=2
   INTEGER, PARAMETER :: mpi_error=3
   INTEGER, PARAMETER :: mpi_status_size=6
   ! mpi_comm
   INTEGER, PARAMETER :: mpi_comm_null=0
   INTEGER, PARAMETER :: mpi_comm_world=1
   INTEGER, PARAMETER :: mpi_comm_self=2
   ! mpi_errhandler
   INTEGER, PARAMETER :: mpi_errhandler_null=0
   INTEGER, PARAMETER :: mpi_errors_are_fatal=1
   INTEGER, PARAMETER :: mpi_errors_return=2
   ! mpi_group
   INTEGER, PARAMETER :: mpi_group_null=0
   INTEGER, PARAMETER :: mpi_group_empty=1
   ! mpi_request
   INTEGER, PARAMETER :: mpi_request_null=0
   ! mpi_op
   INTEGER, PARAMETER :: mpi_op_null=0
   INTEGER, PARAMETER :: mpi_max=1
   INTEGER, PARAMETER :: mpi_min=2
   INTEGER, PARAMETER :: mpi_sum=3
   INTEGER, PARAMETER :: mpi_prod=4
   INTEGER, PARAMETER :: mpi_land=5
   INTEGER, PARAMETER :: mpi_band=6
   INTEGER, PARAMETER :: mpi_lor=7
   INTEGER, PARAMETER :: mpi_bor=8
   INTEGER, PARAMETER :: mpi_lxor=9
   INTEGER, PARAMETER :: mpi_bxor=10
   INTEGER, PARAMETER :: mpi_maxloc=11
   INTEGER, PARAMETER :: mpi_minloc=12
   ! mpi_datatype
   INTEGER :: mpi_datatype_null
   INTEGER, PARAMETER :: mpi_char=1
   INTEGER, PARAMETER :: mpi_short=2
   INTEGER, PARAMETER :: mpi_int=3
   INTEGER, PARAMETER :: mpi_long=4
   INTEGER, PARAMETER :: mpi_unsigned_char=5
   INTEGER, PARAMETER :: mpi_unsigned_short=6
   INTEGER, PARAMETER :: mpi_unsigned=7
   INTEGER, PARAMETER :: mpi_unsigned_long=8
   INTEGER, PARAMETER :: mpi_float=9
   INTEGER, PARAMETER :: mpi_double=10
   INTEGER, PARAMETER :: mpi_long_double=11
   INTEGER, PARAMETER :: mpi_long_long=12
   INTEGER, PARAMETER :: mpi_long_long_int=13
   INTEGER, PARAMETER :: mpi_integer=14
   INTEGER, PARAMETER :: mpi_real=15
   INTEGER, PARAMETER :: mpi_double_precision=16
   INTEGER, PARAMETER :: mpi_complex=17
   INTEGER, PARAMETER :: mpi_double_complex=18
   INTEGER, PARAMETER :: mpi_logical=19
   INTEGER, PARAMETER :: mpi_character=20
   INTEGER, PARAMETER :: mpi_integer1=21
   INTEGER, PARAMETER :: mpi_integer2=22
   INTEGER, PARAMETER :: mpi_integer4=23
   INTEGER, PARAMETER :: mpi_integer8=24
   INTEGER, PARAMETER :: mpi_real4=25
   INTEGER, PARAMETER :: mpi_real8=26
   INTEGER, PARAMETER :: mpi_real16=27
   INTEGER, PARAMETER :: mpi_byte=28
   INTEGER, PARAMETER :: mpi_packed=29
   INTEGER, PARAMETER :: mpi_ub=30
   INTEGER, PARAMETER :: mpi_lb=31
   INTEGER, PARAMETER :: mpi_float_int=32
   INTEGER, PARAMETER :: mpi_double_int=33
   INTEGER, PARAMETER :: mpi_long_int=34
   INTEGER, PARAMETER :: mpi_2int=35
   INTEGER, PARAMETER :: mpi_short_int=36
   INTEGER, PARAMETER :: mpi_long_double_int=37
   INTEGER, PARAMETER :: mpi_2real=38
   INTEGER, PARAMETER :: mpi_2double_precision=39
   INTEGER, PARAMETER :: mpi_2integer=40
   ! mpi-1 error codes and classes
   INTEGER, PARAMETER :: mpi_success=0
   INTEGER, PARAMETER :: mpi_err_buffer=1
   INTEGER, PARAMETER :: mpi_err_count=2
   INTEGER, PARAMETER :: mpi_err_type=3
   INTEGER, PARAMETER :: mpi_err_tag=4
   INTEGER, PARAMETER :: mpi_err_comm=5
   INTEGER, PARAMETER :: mpi_err_rank=6
   INTEGER, PARAMETER :: mpi_err_request=7
   INTEGER, PARAMETER :: mpi_err_root=8
   INTEGER, PARAMETER :: mpi_err_group=9
   INTEGER, PARAMETER :: mpi_err_op=10
   INTEGER, PARAMETER :: mpi_err_topology=11
   INTEGER, PARAMETER :: mpi_err_dims=12
   INTEGER, PARAMETER :: mpi_err_arg=13
   INTEGER, PARAMETER :: mpi_err_unknown=14
   INTEGER, PARAMETER :: mpi_err_truncate=15
   INTEGER, PARAMETER :: mpi_err_other=16
   INTEGER, PARAMETER :: mpi_err_intern=17
   INTEGER, PARAMETER :: mpi_err_in_status=18
   INTEGER, PARAMETER :: mpi_err_pending=19
   ! mpi-2 error codes and classes
   INTEGER, PARAMETER :: mpi_err_access=28
   INTEGER, PARAMETER :: mpi_err_amode=29
   INTEGER, PARAMETER :: mpi_err_assert=30
   INTEGER, PARAMETER :: mpi_err_bad_file=31
   INTEGER, PARAMETER :: mpi_err_base=32
   INTEGER, PARAMETER :: mpi_err_conversion=33
   INTEGER, PARAMETER :: mpi_err_disp=34
   INTEGER, PARAMETER :: mpi_err_dup_datarep=35
   INTEGER, PARAMETER :: mpi_err_file_exists=36
   INTEGER, PARAMETER :: mpi_err_file_in_use=37
   INTEGER, PARAMETER :: mpi_err_file=38
   INTEGER, PARAMETER :: mpi_err_info_key=39
   INTEGER, PARAMETER :: mpi_err_info_nokey=40
   INTEGER, PARAMETER :: mpi_err_info_value=41
   INTEGER, PARAMETER :: mpi_err_info=42
   INTEGER, PARAMETER :: mpi_err_io=43
   INTEGER, PARAMETER :: mpi_err_keyval=44
   INTEGER, PARAMETER :: mpi_err_locktype=45
   INTEGER, PARAMETER :: mpi_err_name=46
   INTEGER, PARAMETER :: mpi_err_no_mem=47
   INTEGER, PARAMETER :: mpi_err_not_same=48
   INTEGER, PARAMETER :: mpi_err_no_space=49
   INTEGER, PARAMETER :: mpi_err_no_such_file=50
   INTEGER, PARAMETER :: mpi_err_port=51
   INTEGER, PARAMETER :: mpi_err_quota=52
   INTEGER, PARAMETER :: mpi_err_read_only=53
   INTEGER, PARAMETER :: mpi_err_rma_conflict=54
   INTEGER, PARAMETER :: mpi_err_rma_sync=55
   INTEGER, PARAMETER :: mpi_err_service=56
   INTEGER, PARAMETER :: mpi_err_size=57
   INTEGER, PARAMETER :: mpi_err_spawn=58
   INTEGER, PARAMETER :: mpi_err_unsupported_datarep=59
   INTEGER, PARAMETER :: mpi_err_unsupported_operation=60
   INTEGER, PARAMETER :: mpi_err_win=61
   INTEGER, PARAMETER :: mpi_err_lastcode=100
   ! permanent keyvals
   INTEGER, PARAMETER :: mpi_keyval_invalid=0
   INTEGER, PARAMETER :: mpi_tag_ub=5
   INTEGER, PARAMETER :: mpi_host=6
   INTEGER, PARAMETER :: mpi_io=7
   INTEGER, PARAMETER :: mpi_wtime_is_global=8
   ! results of the compare operations
   INTEGER, PARAMETER :: mpi_ident=0
   INTEGER, PARAMETER :: mpi_congruent=1
   INTEGER, PARAMETER :: mpi_similar=2
   INTEGER, PARAMETER :: mpi_unequal=3
   ! topology types
   INTEGER, PARAMETER :: mpi_graph=1
   INTEGER, PARAMETER :: mpi_cart=2
   ! misc constants
   INTEGER, PARAMETER :: mpi_max_processor_name=256
   INTEGER, PARAMETER :: mpi_max_error_string=256
   INTEGER, PARAMETER :: mpi_bsend_overhead=32
   INTEGER, PARAMETER :: mpi_undefined=-3
   INTEGER, PARAMETER :: mpi_any_source=-2
   INTEGER, PARAMETER :: mpi_proc_null=-1
   INTEGER, PARAMETER :: mpi_any_tag=-1
   ! mpi-2
   INTEGER, PARAMETER :: mpi_fundamental=-1
   ! mpi-2 io
   INTEGER, PARAMETER :: mpi_mode_rdonly=2
   INTEGER, PARAMETER :: mpi_mode_rdwr=8
   INTEGER, PARAMETER :: mpi_mode_wronly=4
   INTEGER, PARAMETER :: mpi_mode_create=1
   INTEGER, PARAMETER :: mpi_mode_delete_on_close=16
   INTEGER, PARAMETER :: mpi_mode_unique_open=32
   INTEGER, PARAMETER :: mpi_mode_excl=64
   INTEGER, PARAMETER :: mpi_mode_append=128
   INTEGER, PARAMETER :: mpi_mode_sequential=256
   INTEGER, PARAMETER :: mpi_file_null=0
   INTEGER, PARAMETER :: mpi_max_datarep_string=128
   INTEGER, PARAMETER :: mpi_seek_set=600
   INTEGER, PARAMETER :: mpi_seek_cur=602
   INTEGER, PARAMETER :: mpi_seek_end=604
   INTEGER, PARAMETER :: mpio_request_null=0
   INTEGER(kind=8), PARAMETER :: mpi_displacement_current=-54278278
   INTEGER, PARAMETER :: mpi_order_c=56
   INTEGER, PARAMETER :: mpi_order_fortran=57
   INTEGER, PARAMETER :: mpi_distribute_block=121
   INTEGER, PARAMETER :: mpi_distribute_cyclic=122
   INTEGER, PARAMETER :: mpi_distribute_none=123
   INTEGER, PARAMETER :: mpi_distribute_dflt_darg=-49767
   ! mpi-2 section 4.10
   INTEGER, PARAMETER :: mpi_info_null=0
   INTEGER, PARAMETER :: mpi_max_info_key=255
   INTEGER, PARAMETER :: mpi_max_info_val=1024
   ! kind values for mpi-2
   INTEGER, PARAMETER :: mpi_offset_kind=8
   INTEGER, PARAMETER :: mpi_address_kind=8
   ! thread-safety support levels
   INTEGER, PARAMETER :: mpi_thread_single=0
   INTEGER, PARAMETER :: mpi_thread_funneled=1
   INTEGER, PARAMETER :: mpi_thread_serialized=2
   INTEGER, PARAMETER :: mpi_thread_multiple=3
   END MODULE SU_MPI_SPATIAL_D
