   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.7 (r4786) - 21 Feb 2013 15:53
   !
   !      ==================================================================
   MODULE INPUTVISUALIZATION_T
   IMPLICIT NONE
   SAVE 
   ! PV3VisOnly: Whether or not to run in visualization mode only.
   LOGICAL :: pv3visonly
   END MODULE INPUTVISUALIZATION_T
