   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.10 (r5363) -  9 Sep 2014 09:53
   !
   !  Differentiation of computeleastsquaresregression in reverse (adjoint) mode (with options i4 dr8 r8 noISIZE):
   !   gradient     of useful results: m y b
   !   with respect to varying inputs: y
   !
   !      ******************************************************************
   !      *                                                                *
   !      * File:          computeLeastSquaresRegression.f90               *
   !      * Author:        C.A.(Sandy) Mader                               *
   !      * Starting date: 10-14-2009                                      *
   !      * Last modified: 10-14-2009                                      *
   !      *                                                                *
   !      ******************************************************************
   !
   SUBROUTINE COMPUTELEASTSQUARESREGRESSION_B(y, yd, x, npts, m, md, b, bd)
   !
   !      ******************************************************************
   !      *                                                                *
   !      * Computes the slope of best fit for a set of x,y data of length *
   !      * npts                                                           *
   !      *                                                                *
   !      ******************************************************************
   !
   USE PRECISION
   IMPLICIT NONE
   !Subroutine arguments 
   INTEGER(kind=inttype) :: npts
   REAL(kind=realtype), DIMENSION(npts) :: x, y
   REAL(kind=realtype), DIMENSION(npts) :: yd
   REAL(kind=realtype) :: m, b
   REAL(kind=realtype) :: md, bd
   !local variables
   REAL(kind=realtype) :: sumx, sumy, sumx2, sumxy
   REAL(kind=realtype) :: sumyd, sumxyd
   INTEGER(kind=inttype) :: i
   REAL(kind=realtype) :: tempd
   REAL(kind=realtype) :: tempd0
   !begin execution
   sumx = 0.0
   sumx2 = 0.0
   DO i=1,npts
   sumx = sumx + x(i)
   sumx2 = sumx2 + x(i)*x(i)
   END DO
   tempd0 = md/(npts*sumx2-sumx**2)
   tempd = bd/(npts*sumx2-sumx**2)
   sumyd = sumx2*tempd - sumx*tempd0
   sumxyd = npts*tempd0 - sumx*tempd
   DO i=npts,1,-1
   yd(i) = yd(i) + sumyd + x(i)*sumxyd
   END DO
   END SUBROUTINE COMPUTELEASTSQUARESREGRESSION_B
