!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3375) - 10 Feb 2010 15:08
!
!
!      ******************************************************************
!      *                                                                *
!      * File:          bcTurbFarfield.f90                              *
!      * Author:        Georgi Kalitzin, Edwin van der Weide            *
!      * Starting date: 06-15-2003                                      *
!      * Last modified: 06-12-2005                                      *
!      *                                                                *
!      ******************************************************************
!
SUBROUTINE BCTURBFARFIELD_CD(nn)
  USE BCTYPES_SPATIAL_D
  USE CONSTANTS_SPATIAL_D
  USE BLOCKPOINTERS_SPATIAL_D
  USE FLOWVARREFSTATE_SPATIAL_D
  IMPLICIT NONE
!
!      ******************************************************************
!      *                                                                *
!      * bcTurbFarfield applies the implicit treatment of the           *
!      * farfield boundary condition to subface nn. As the farfield     *
!      * boundary condition is independent of the turbulence model,     *
!      * this routine is valid for all models. It is assumed that the   *
!      * pointers in blockPointers are already set to the correct       *
!      * block on the correct grid level.                               *
!      *                                                                *
!      ******************************************************************
!
!
!      Subroutine arguments.
!
  INTEGER(kind=inttype), INTENT(IN) :: nn
!
!      Local variables.
!
  INTEGER(kind=inttype) :: i, j, l
  REAL(kind=realtype) :: nnx, nny, nnz, dot
  REAL(kind=realtype), DIMENSION(:, :, :, :), POINTER :: bmt
  REAL(kind=realtype), DIMENSION(:, :, :), POINTER :: bvt
!
!      ******************************************************************
!      *                                                                *
!      * Begin execution                                                *
!      *                                                                *
!      ******************************************************************
!
! Set the pointers for bmt and bvt, depending on the block face
! on which the subface is located.
  SELECT CASE  (bcfaceid(nn)) 
  CASE (imin) 
    bmt => bmti1
    bvt => bvti1
  CASE (imax) 
    bmt => bmti2
    bvt => bvti2
  CASE (jmin) 
    bmt => bmtj1
    bvt => bvtj1
  CASE (jmax) 
    bmt => bmtj2
    bvt => bvtj2
  CASE (kmin) 
    bmt => bmtk1
    bvt => bvtk1
  CASE (kmax) 
    bmt => bmtk2
    bvt => bvtk2
  END SELECT
! Loop over the faces of the subfaces and set the values of
! bmt and bvt for an implicit treatment.
  DO j=bcdata(nn)%jcbeg,bcdata(nn)%jcend
    DO i=bcdata(nn)%icbeg,bcdata(nn)%icend
! Store the three components of the unit normal a bit easier.
      nnx = bcdata(nn)%norm(i, j, 1)
      nny = bcdata(nn)%norm(i, j, 2)
      nnz = bcdata(nn)%norm(i, j, 3)
! Determine the dot product between the outward pointing
! normal and the free stream velocity direction and add the
! possible grid velocity.
      dot = nnx*winf(ivx) + nny*winf(ivy) + nnz*winf(ivz) - bcdata(nn)%&
&        rface(i, j)
! Determine whether we are dealing with an inflow or
! outflow boundary here.
      IF (dot .GT. zero) THEN
! Outflow. Simply extrapolation or zero Neumann BC
! of the turbulent variables.
        DO l=nt1,nt2
          bmt(i, j, l, l) = -one
        END DO
      ELSE
! Inflow. Turbulent variables are prescribed.
        DO l=nt1,nt2
          bvt(i, j, l) = winf(l)
        END DO
      END IF
    END DO
  END DO
END SUBROUTINE BCTURBFARFIELD_CD
