1 turbresidual_block: (TC19) Equality test on reals is not reliable
2 eintarray: (TC19) Equality test on reals is not reliable
3 block_res_spatial: (DF02) Potential aliasing in calling function setpointersofftsinstance, between arguments 2 3
4 block_res_spatial: (DF02) Potential aliasing in calling function setpointersofftsinstance, between arguments 2 3
5 block_res_spatial: (DF02) Potential aliasing in calling function setpointersofftsinstance, between arguments 2 3
6 block_res_spatial: (DF02) Potential aliasing in calling function setpointersofftsinstance, between arguments 2 3
7 block_res_spatial: Command: Output variable(s) *x have their derivative modified in block_res_spatial: added to dependents
8 applyallbc_block: (TC32) Conflicting numbers of arguments for procedure terminate, was 2, is here 3
9 applyallbc_block: (TC32) Conflicting numbers of arguments for procedure terminate, was 2, is here 3
10 sa_block: (TC33) External procedure sasolve_mod is not declared
11 metric_block: (TC33) External procedure flowdoms is not declared
12 metric_block: (DF03) variable *ss[i,j,1] is used before initialized
13 metric_block: (DF03) variable *ss[i,j,2] is used before initialized
14 metric_block: (DF03) variable *ss[i,j,3] is used before initialized
15 setpointersofftsinstance: (TC33) External procedure setpointers is not declared
16 setpointersofftsinstance: (TC33) External procedure flowdoms is not declared
17 invisciddissfluxmatrix: (TC19) Equality test on reals is not reliable
18 invisciddissfluxmatrixcoarse: (TC19) Equality test on reals is not reliable
19 invisciddissfluxscalar: (TC19) Equality test on reals is not reliable
20 invisciddissfluxscalarcoarse: (TC19) Equality test on reals is not reliable
21 inviscidupwindflux: (TC19) Equality test on reals is not reliable
22 riemannflux: (TC30) Type mismatch in argument 9 of procedure etotarray, was INTEGER,kind=inttype , is here REAL,intType 
23 riemannflux: (TC32) Conflicting numbers of arguments for procedure terminate, was 2, is here 3
24 riemannflux: (TC32) Conflicting numbers of arguments for procedure terminate, was 2, is here 3
25 viscousflux: (TC32) Conflicting numbers of arguments for procedure terminate, was 2, is here 3
26 viscousflux: (TC19) Equality test on reals is not reliable
27 viscousflux: (AD12) User help requested: unknown dimension 3 of array viscsubface
28 bceulerwall: (TC30) Type mismatch in argument 10 of procedure setbcpointers, was INTEGER,kind=inttype , is here REAL,intType 
29 bcfarfield: (TC30) Type mismatch in argument 10 of procedure setbcpointers, was INTEGER,kind=inttype , is here REAL,intType 
30 bcnswalladiabatic: (TC30) Type mismatch in argument 10 of procedure setbcpointers, was INTEGER,kind=inttype , is here REAL,intType 
31 bcnswallisothermal: (TC30) Type mismatch in argument 10 of procedure setbcpointers, was INTEGER,kind=inttype , is here REAL,intType 
32 extrapolate2ndhalo: (TC30) Type mismatch in argument 10 of procedure setbcpointers, was INTEGER,kind=inttype , is here REAL,intType 
33 sasolve: (TC33) External procedure prodkatolaunder is not declared
34 sasolve: (TC33) External procedure turbadvection is not declared
35 sasolve: (TC33) External procedure unsteadyturbterm is not declared
36 curvetupyp: (TC32) Conflicting numbers of arguments for procedure terminate, was 2, is here 3
37 curvetupyp: (TC32) Conflicting numbers of arguments for procedure terminate, was 2, is here 3
38 unsteadyturbspectral: (TC33) External procedure setpointers is not declared
39 unsteadyturbspectral: (TC33) External procedure flowdoms is not declared
40 vfeddyviscosity: (TC33) External procedure vfscale is not declared
41 applyallturbbc: (TC33) External procedure setpointers is not declared
42 bcturbtreatment: (TC33) External procedure bcturbinterface is not declared
43 bcturbwall: (TC16) Type mismatch in assignment: INTEGER,kind=inttype  receives REAL,intType 
44 bcturbwall: (TC16) Type mismatch in assignment: INTEGER,kind=inttype  receives REAL,intType 
45 bcturbwall: (TC16) Type mismatch in assignment: INTEGER,kind=inttype  receives REAL,intType 
46 bcturbwall: (TC16) Type mismatch in assignment: INTEGER,kind=inttype  receives REAL,intType 
47 applyallturbbcthisblock: (TC19) Equality test on reals is not reliable
48 applyallturbbcthisblock: (TC33) External procedure turb2ndhalo is not declared
49 bl: (TC33) External procedure setpointers is not declared
50 computeetotcellcpfit: (TC19) Equality test on reals is not reliable
