!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3375) - 10 Feb 2010 15:08
!
!
!      ******************************************************************
!      *                                                                *
!      * File:          sa.f90                                          *
!      * Author:        Georgi Kalitzin, Edwin van der Weide            *
!      * Starting date: 06-11-2003                                      *
!      * Last modified: 04-12-2005                                      *
!      *                                                                *
!      ******************************************************************
!
SUBROUTINE SA_BLOCK_CD(resonly)
  USE ITERATION_SPATIAL_D
  USE INPUTTIMESPECTRAL_SPATIAL_D
  USE BLOCKPOINTERS_SPATIAL_D
  IMPLICIT NONE
!
!      ******************************************************************
!      *                                                                *
!      * sa solves the transport equation for the Spalart-Allmaras      *
!      * turbulence model in a segregated manner using a diagonal       *
!      * dominant ADI-scheme.                                           *
!      *                                                                *
!      ******************************************************************
!
!
!      Subroutine argument.
!
  LOGICAL, INTENT(IN) :: resonly
!
!      Local variables.
!
  INTEGER(kind=inttype) :: nn, sps
  EXTERNAL SASOLVE_MOD
!
!      ******************************************************************
!      *                                                                *
!      * Begin execution                                                *
!      *                                                                *
!      ******************************************************************
!
! Compute the time derivative for the time spectral mode.
  CALL UNSTEADYTURBSPECTRAL_CD(itu1, itu1)
! Loop over the number of spectral modes and local blocks.
! Set the arrays for the boundary condition treatment.
  CALL BCTURBTREATMENT_CD()
! Solve the transport equation for nuTilde.
  CALL SASOLVE_MOD(resonly)
! The eddy viscosity and the boundary conditions are only
! applied if an actual update has been computed in saSolve.
  IF (.NOT.resonly) THEN
! Compute the corresponding eddy viscosity.
    CALL SAEDDYVISCOSITY_CD()
! Set the halo values for the turbulent variables.
! We are on the finest mesh, so the second layer of halo
! cells must be computed as well.
    CALL APPLYALLTURBBCTHISBLOCK_CD(.true.)
! Write the loglaw for a flat plate boundary layer.
! call writeLoglaw
  END IF
END SUBROUTINE SA_BLOCK_CD
