   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.4 (r3375) - 10 Feb 2010 15:08
   !
   !  Differentiation of normalvelocities_block in forward (tangent) mode:
   !   variations   of useful results: *(*bcdata.rface)
   !   with respect to varying inputs: *sfacei *sfacej *sfacek
   !
   !      ******************************************************************
   !      *                                                                *
   !      * File:          normalVelocities.f90                            *
   !      * Author:        Edwin van der Weide, C.A.(Sandy) Mader          *
   !      * Starting date: 07-15-2011                                      *
   !      * Last modified: 07-15-2011                                      *
   !      *                                                                *
   !      ******************************************************************
   !
SUBROUTINE NORMALVELOCITIES_BLOCK_EXTRA_D(sps)
  USE BCTYPES
  USE BLOCKPOINTERS_D
  USE ITERATION
  USE DIFFSIZES
  !  Hint: ISIZE2OFbcdata should be the size of dimension 2 of array bcdata
  IMPLICIT NONE
  !
  !      ******************************************************************
  !      *                                                                *
  !      * normalVelocities_block computes the normal grid                *
  !      * velocities of some boundary faces of the moving blocks for     *
  !      * spectral mode sps. Just the current ground level is considered.*
  !      * This is essentially a single level,single block version of     *
  !      * normalVelocitiesAllLevels.                                     *
  !      *                                                                *
  !      ******************************************************************
  !
  !
  !      Subroutine arguments.
  !
  INTEGER(kind=inttype), INTENT(IN) :: sps
  !
  !      Local variables.
  !
  INTEGER(kind=inttype) :: nlevels, level, nn, mm
  INTEGER(kind=inttype) :: i, j
  REAL(kind=realtype) :: weight, mult
  REAL(kind=realtype), DIMENSION(:, :), POINTER :: sface
  REAL(kind=realtype), DIMENSION(:, :), POINTER :: sfaced
  REAL(kind=realtype), DIMENSION(:, :, :), POINTER :: ss
  REAL(kind=realtype) :: arg1
  INTEGER :: ii1
  !INTEGER :: ii1
  INTRINSIC ASSOCIATED
  INTRINSIC SQRT
  !
  !      ******************************************************************
  !      *                                                                *
  !      * Begin execution                                                *
  !      *                                                                *
  !      ******************************************************************
  !
  !print *,'in normal',addgridvelocities
  ! Check for a moving block. As it is possible that in a
  ! multidisicplinary environment additional grid velocities
  ! are set, the test should be done on addGridVelocities
  ! and not on blockIsMoving.
  IF (addgridvelocities) THEN
     DO ii1=1,nbocos!ISIZE2OFbcdata
         IF (ASSOCIATED(bcdata(ii1)%rface)) THEN
            bcdatad(ii1)%rface = 0.0
         end IF
     END DO
     !
     !            ************************************************************
     !            *                                                          *
     !            * Determine the normal grid velocities of the boundaries.  *
     !            * As these values are based on the unit normal. A division *
     !            * by the length of the normal is needed.                   *
     !            * Furthermore the boundary unit normals are per definition *
     !            * outward pointing, while on the iMin, jMin and kMin       *
     !            * boundaries the face normals are inward pointing. This    *
     !            * is taken into account by the factor mult.                *
     !            *                                                          *
     !            ************************************************************
     !
     !print *,'looping'
     ! Loop over the boundary subfaces.
     bocoloop:DO mm=1,nbocos
        ! Check whether rFace is allocated.
        IF (ASSOCIATED(bcdata(mm)%rface)) THEN
           ! Determine the block face on which the subface is
           ! located and set some variables accordingly.
           SELECT CASE  (bcfaceid(mm)) 
           CASE (imin) 
              mult = -one
              ss => si(1, :, :, :)
              sfaced => sfaceid(1, :, :)
              sface => sfacei(1, :, :)
           CASE (imax) 
              mult = one
              ss => si(il, :, :, :)
              sfaced => sfaceid(il, :, :)
              sface => sfacei(il, :, :)
           CASE (jmin) 
              mult = -one
              ss => sj(:, 1, :, :)
              sfaced => sfacejd(:, 1, :)
              sface => sfacej(:, 1, :)
           CASE (jmax) 
              mult = one
              ss => sj(:, jl, :, :)
              sfaced => sfacejd(:, jl, :)
              sface => sfacej(:, jl, :)
           CASE (kmin) 
              mult = -one
              ss => sk(:, :, 1, :)
              sfaced => sfacekd(:, :, 1)
              sface => sfacek(:, :, 1)
           CASE (kmax) 
              mult = one
              ss => sk(:, :, kl, :)
              sfaced => sfacekd(:, :, kl)
              sface => sfacek(:, :, kl)
           END SELECT
           ! Loop over the faces of the subface.
           DO j=bcdata(mm)%jcbeg,bcdata(mm)%jcend
              DO i=bcdata(mm)%icbeg,bcdata(mm)%icend
                 ! Compute the inverse of the length of the normal
                 ! vector and possibly correct for inward pointing.
                 arg1 = ss(i, j, 1)**2 + ss(i, j, 2)**2 + ss(i, j, 3)**2
                 weight = SQRT(arg1)
                 IF (weight .GT. zero) weight = mult/weight
                 ! Compute the normal velocity based on the outward
                 ! pointing unit normal.
                 bcdatad(mm)%rface(i, j) = weight*sfaced(i, j)
                 bcdata(mm)%rface(i, j) = weight*sface(i, j)
              END DO
           END DO
        END IF
     END DO bocoloop
  ELSE
     ! Block is not moving. Loop over the boundary faces and set
     ! the normal grid velocity to zero if allocated.
     DO mm=1,nbocos
        IF (ASSOCIATED(bcdata(mm)%rface)) THEN
           bcdatad(mm)%rface = 0.0
           bcdata(mm)%rface = zero
        END IF
     END DO
     !print *,'endloop'
     DO ii1=1,nbocos!ISIZE2OFbcdata
        IF (ASSOCIATED(bcdata(ii1)%rface)) THEN
           bcdatad(ii1)%rface = 0.0
        END IF
     END DO
 
  END IF
  !print *,'leaving normal'
END SUBROUTINE NORMALVELOCITIES_BLOCK_EXTRA_D
