!        generated by tapenade     (inria, tropics team)
!  tapenade 3.10 (r5363) -  9 sep 2014 09:53
!
!  differentiation of computespeedofsoundsquared in forward (tangent) mode (with options i4 dr8 r8):
!   variations   of useful results: *aa
!   with respect to varying inputs: *p *w
!   plus diff mem management of: aa:in p:in w:in
!
!      ******************************************************************
!      *                                                                *
!      * file:          computespeedofsoundsquared.f90                  *
!      * author:        gaetan k.w. kenway                              *
!      * starting date: 01-20-2014                                      *
!      * last modified: 01-20-2014                                      *
!      *                                                                *
!      ******************************************************************
!
subroutine computespeedofsoundsquared_d()
!
!      ******************************************************************
!      *                                                                *
!      * computespeedofsoundsquared does what it says.                  *
!      *                                                                *
!      ******************************************************************
!
  use blockpointers
  use constants
  use flowvarrefstate
  use inputphysics
  use iteration
  implicit none
!
!      local variables.
!
  logical :: correctfork
  real(kind=realtype), parameter :: twothird=two*third
  integer(kind=inttype) :: i, j, k, ii
  real(kind=realtype) :: pp
  real(kind=realtype) :: ppd
! determine if we need to correct for k
  if (kpresent) then
    if (currentlevel .le. groundlevel .or. turbcoupled) then
      correctfork = .true.
    else
      correctfork = .false.
    end if
  else
    correctfork = .false.
  end if
  if (correctfork) then
    aad = 0.0_8
    do k=1,ke
      do j=1,je
        do i=1,ie
          ppd = pd(i, j, k) - twothird*(wd(i, j, k, irho)*w(i, j, k, &
&           itu1)+w(i, j, k, irho)*wd(i, j, k, itu1))
          pp = p(i, j, k) - twothird*w(i, j, k, irho)*w(i, j, k, itu1)
          aad(i, j, k) = (gamma(i, j, k)*ppd*w(i, j, k, irho)-gamma(i, j&
&           , k)*pp*wd(i, j, k, irho))/w(i, j, k, irho)**2
          aa(i, j, k) = gamma(i, j, k)*pp/w(i, j, k, irho)
        end do
      end do
    end do
  else
    aad = 0.0_8
    do k=1,ke
      do j=1,je
        do i=1,ie
          aad(i, j, k) = (gamma(i, j, k)*pd(i, j, k)*w(i, j, k, irho)-&
&           gamma(i, j, k)*p(i, j, k)*wd(i, j, k, irho))/w(i, j, k, irho&
&           )**2
          aa(i, j, k) = gamma(i, j, k)*p(i, j, k)/w(i, j, k, irho)
        end do
      end do
    end do
  end if
end subroutine computespeedofsoundsquared_d
