   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.10 (r5363) -  9 Sep 2014 09:53
   !
   !  Differentiation of computeleastsquaresregression in forward (tangent) mode (with options i4 dr8 r8):
   !   variations   of useful results: m b
   !   with respect to varying inputs: y
   !
   !      ******************************************************************
   !      *                                                                *
   !      * File:          computeLeastSquaresRegression.f90               *
   !      * Author:        C.A.(Sandy) Mader                               *
   !      * Starting date: 10-14-2009                                      *
   !      * Last modified: 10-14-2009                                      *
   !      *                                                                *
   !      ******************************************************************
   !
   SUBROUTINE COMPUTELEASTSQUARESREGRESSION_D(y, yd, x, npts, m, md, b, bd)
   !
   !      ******************************************************************
   !      *                                                                *
   !      * Computes the slope of best fit for a set of x,y data of length *
   !      * npts                                                           *
   !      *                                                                *
   !      ******************************************************************
   !
   USE PRECISION
   IMPLICIT NONE
   !Subroutine arguments 
   INTEGER(kind=inttype) :: npts
   REAL(kind=realtype), DIMENSION(npts) :: x, y
   REAL(kind=realtype), DIMENSION(npts) :: yd
   REAL(kind=realtype) :: m, b
   REAL(kind=realtype) :: md, bd
   !local variables
   REAL(kind=realtype) :: sumx, sumy, sumx2, sumxy
   REAL(kind=realtype) :: sumyd, sumxyd
   INTEGER(kind=inttype) :: i
   !begin execution
   sumx = 0.0
   sumy = 0.0
   sumx2 = 0.0
   sumxy = 0.0
   sumyd = 0.0_8
   sumxyd = 0.0_8
   DO i=1,npts
   sumx = sumx + x(i)
   sumyd = sumyd + yd(i)
   sumy = sumy + y(i)
   sumx2 = sumx2 + x(i)*x(i)
   sumxyd = sumxyd + x(i)*yd(i)
   sumxy = sumxy + x(i)*y(i)
   END DO
   md = (npts*sumxyd-sumx*sumyd)/(npts*sumx2-sumx**2)
   m = (npts*sumxy-sumy*sumx)/(npts*sumx2-sumx**2)
   bd = (sumx2*sumyd-sumx*sumxyd)/(npts*sumx2-sumx**2)
   b = (sumy*sumx2-sumx*sumxy)/(npts*sumx2-sumx**2)
   END SUBROUTINE COMPUTELEASTSQUARESREGRESSION_D
