   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.7 (r4786) - 21 Feb 2013 15:53
   !
   !  Differentiation of getcostfuncmat in forward (tangent) mode (with options i4 dr8 r8):
   !   variations   of useful results: *costfuncmat
   !   with respect to varying inputs: pinf pref lengthref surfaceref
   !                machcoef dragdirection liftdirection alpha beta
   !   Plus diff mem management of: costfuncmat:in
   SUBROUTINE GETCOSTFUNCMAT_D(alpha, alphad, beta, betad, liftindex)
   USE FLOWVARREFSTATE
   USE INPUTTIMESPECTRAL
   USE COSTFUNCTIONS
   USE INPUTPHYSICS
   USE CONSTANTS
   IMPLICIT NONE
   !
   !     ******************************************************************
   !     *                                                                *
   !     * Compute the cost function vector needed to calculate           *
   !     * dIdw, dIdx and dIda.                                            *
   !     *                                                                *
   !     ******************************************************************
   !
   !Subroutine Vars Input/Ouput
   REAL(kind=realtype), INTENT(IN) :: alpha, beta
   REAL(kind=realtype), INTENT(IN) :: alphad, betad
   INTEGER(kind=inttype), INTENT(IN) :: liftindex
   ! Working vars
   INTEGER(kind=inttype) :: sps
   REAL(kind=realtype) :: fact, scaledim
   REAL(kind=realtype) :: factd, scaledimd
   CALL ADJUSTINFLOWANGLE_D(alpha, alphad, beta, betad, liftindex)
   scaledimd = (prefd*pinf-pref*pinfd)/pinf**2
   scaledim = pref/pinf
   factd = -(two*gammainf*lref**2*((pinfd*surfaceref+pinf*surfacerefd)*&
   &    machcoef**2*scaledim+pinf*surfaceref*(2*machcoef*machcoefd*scaledim+&
   &    machcoef**2*scaledimd))/(gammainf*pinf*machcoef**2*surfaceref*lref**&
   &    2*scaledim)**2)
   fact = two/(gammainf*pinf*machcoef**2*surfaceref*lref**2*scaledim)
   costfuncmatd = 0.0_8
   costfuncmat = zero
   costfuncmatd = 0.0_8
   DO sps=1,ntimeintervalsspectral
   ! Just set the ones we know
   costfuncmatd(:, costfunclift, sps) = (/liftdirectiond(1), &
   &      liftdirectiond(2), liftdirectiond(3), 0.0_8, 0.0_8, 0.0_8/)
   costfuncmat(:, costfunclift, sps) = (/liftdirection(1), &
   &      liftdirection(2), liftdirection(3), zero, zero, zero/)
   costfuncmatd(:, costfuncdrag, sps) = (/dragdirectiond(1), &
   &      dragdirectiond(2), dragdirectiond(3), 0.0_8, 0.0_8, 0.0_8/)
   costfuncmat(:, costfuncdrag, sps) = (/dragdirection(1), &
   &      dragdirection(2), dragdirection(3), zero, zero, zero/)
   costfuncmatd(:, costfuncliftcoef, sps) = (/liftdirectiond(1)*fact+&
   &      liftdirection(1)*factd, liftdirectiond(2)*fact+liftdirection(2)*&
   &      factd, liftdirectiond(3)*fact+liftdirection(3)*factd, 0.0_8, 0.0_8&
   &      , 0.0_8/)
   costfuncmat(:, costfuncliftcoef, sps) = (/liftdirection(1)*fact, &
   &      liftdirection(2)*fact, liftdirection(3)*fact, zero, zero, zero/)
   costfuncmatd(:, costfuncdragcoef, sps) = (/dragdirectiond(1)*fact+&
   &      dragdirection(1)*factd, dragdirectiond(2)*fact+dragdirection(2)*&
   &      factd, dragdirectiond(3)*fact+dragdirection(3)*factd, 0.0_8, 0.0_8&
   &      , 0.0_8/)
   costfuncmat(:, costfuncdragcoef, sps) = (/dragdirection(1)*fact, &
   &      dragdirection(2)*fact, dragdirection(3)*fact, zero, zero, zero/)
   costfuncmatd(:, costfuncforcex, sps) = 0.0_8
   costfuncmat(:, costfuncforcex, sps) = (/one, zero, zero, zero, zero&
   &      , zero/)
   costfuncmatd(:, costfuncforcey, sps) = 0.0_8
   costfuncmat(:, costfuncforcey, sps) = (/zero, one, zero, zero, zero&
   &      , zero/)
   costfuncmatd(:, costfuncforcez, sps) = 0.0_8
   costfuncmat(:, costfuncforcez, sps) = (/zero, zero, one, zero, zero&
   &      , zero/)
   costfuncmatd(:, costfuncforcexcoef, sps) = (/factd, 0.0_8, 0.0_8, &
   &      0.0_8, 0.0_8, 0.0_8/)
   costfuncmat(:, costfuncforcexcoef, sps) = (/fact, zero, zero, zero, &
   &      zero, zero/)
   costfuncmatd(:, costfuncforceycoef, sps) = (/0.0_8, factd, 0.0_8, &
   &      0.0_8, 0.0_8, 0.0_8/)
   costfuncmat(:, costfuncforceycoef, sps) = (/zero, fact, zero, zero, &
   &      zero, zero/)
   costfuncmatd(:, costfuncforcezcoef, sps) = (/0.0_8, 0.0_8, factd, &
   &      0.0_8, 0.0_8, 0.0_8/)
   costfuncmat(:, costfuncforcezcoef, sps) = (/zero, zero, fact, zero, &
   &      zero, zero/)
   costfuncmatd(:, costfuncmomx, sps) = 0.0_8
   costfuncmat(:, costfuncmomx, sps) = (/zero, zero, zero, one, zero, &
   &      zero/)
   costfuncmatd(:, costfuncmomy, sps) = 0.0_8
   costfuncmat(:, costfuncmomy, sps) = (/zero, zero, zero, zero, one, &
   &      zero/)
   costfuncmatd(:, costfuncmomz, sps) = 0.0_8
   costfuncmat(:, costfuncmomz, sps) = (/zero, zero, zero, zero, zero, &
   &      one/)
   ! update fact to get the moment
   factd = (factd*lengthref*lref-fact*lref*lengthrefd)/(lengthref*lref)&
   &      **2
   fact = fact/(lengthref*lref)
   costfuncmatd(:, costfuncmomxcoef, sps) = (/0.0_8, 0.0_8, 0.0_8, &
   &      factd, 0.0_8, 0.0_8/)
   costfuncmat(:, costfuncmomxcoef, sps) = (/zero, zero, zero, fact, &
   &      zero, zero/)
   costfuncmatd(:, costfuncmomycoef, sps) = (/0.0_8, 0.0_8, 0.0_8, &
   &      0.0_8, factd, 0.0_8/)
   costfuncmat(:, costfuncmomycoef, sps) = (/zero, zero, zero, zero, &
   &      fact, zero/)
   costfuncmatd(:, costfuncmomzcoef, sps) = (/0.0_8, 0.0_8, 0.0_8, &
   &      0.0_8, 0.0_8, factd/)
   costfuncmat(:, costfuncmomzcoef, sps) = (/zero, zero, zero, zero, &
   &      zero, fact/)
   END DO
   costfuncmatd = costfuncmatd/ntimeintervalsspectral
   costfuncmat = costfuncmat/ntimeintervalsspectral
   END SUBROUTINE GETCOSTFUNCMAT_D
