   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.7 (r4786) - 21 Feb 2013 15:53
   !
   !  Differentiation of computetsderivatives in reverse (adjoint) mode (with options i4 dr8 r8):
   !   gradient     of useful results: lengthref dragdirection liftdirection
   !                moment dcdalphadot coef0 force dcdalpha
   !   with respect to varying inputs: machgrid lengthref machcoef
   !                dragdirection liftdirection moment force
   !
   !     ******************************************************************
   !     *                                                                *
   !     * File:          computeTSDerivatives.f90                        *
   !     * Author:        C.A.(Sandy) Mader, G. Kenway                    *
   !     * Starting date: 11-25-2009                                      *
   !     * Last modified: 11-26-2009                                      *
   !     *                                                                *
   !     ******************************************************************
   !
   SUBROUTINE COMPUTETSDERIVATIVES_B(force, forceb, moment, momentb, &
   &  liftindex, coef0, coef0b, dcdalpha, dcdalphab, dcdalphadot, &
   &  dcdalphadotb, dcdq, dcdqdot)
   USE MONITOR
   USE SECTION
   USE INPUTTIMESPECTRAL
   USE INPUTTSSTABDERIV
   USE INPUTPHYSICS
   USE COMMUNICATION
   USE INPUTMOTION
   USE FLOWVARREFSTATE
   IMPLICIT NONE
   !
   !     ******************************************************************
   !     *                                                                *
   !     * Computes the stability derivatives based on the time spectral  *
   !     * solution of a given mesh. Takes in the force coefficients at   *
   !     * all time instantces and computes the agregate parameters       *
   !     *                                                                *
   !     ******************************************************************
   !
   !
   !     Subroutine arguments.
   !
   REAL(kind=realtype), DIMENSION(3, ntimeintervalsspectral) :: force, &
   &  moment
   REAL(kind=realtype), DIMENSION(3, ntimeintervalsspectral) :: forceb, &
   &  momentb
   REAL(kind=realtype), DIMENSION(8) :: dcdq, dcdqdot
   REAL(kind=realtype), DIMENSION(8) :: dcdalpha, dcdalphadot
   REAL(kind=realtype), DIMENSION(8) :: dcdalphab, dcdalphadotb
   REAL(kind=realtype), DIMENSION(8) :: coef0
   REAL(kind=realtype), DIMENSION(8) :: coef0b
   INTEGER(kind=inttype) :: liftindex
   ! Working Variables
   REAL(kind=realtype), DIMENSION(ntimeintervalsspectral, 8) :: basecoef
   REAL(kind=realtype), DIMENSION(ntimeintervalsspectral, 8) :: basecoefb
   REAL(kind=realtype), DIMENSION(8) :: coef0dot
   REAL(kind=realtype), DIMENSION(8) :: coef0dotb
   REAL(kind=realtype), DIMENSION(ntimeintervalsspectral, 8) :: &
   &  resbasecoef
   REAL(kind=realtype), DIMENSION(ntimeintervalsspectral, 8) :: &
   &  resbasecoefb
   REAL(kind=realtype), DIMENSION(ntimeintervalsspectral) :: &
   &  intervalalpha, intervalalphadot
   REAL(kind=realtype), DIMENSION(ntimeintervalsspectral) :: intervalmach&
   &  , intervalmachdot
   REAL(kind=realtype), DIMENSION(nsections) :: t
   REAL(kind=realtype) :: alpha, beta
   INTEGER(kind=inttype) :: i, sps, nn
   !speed of sound: for normalization of q derivatives
   REAL(kind=realtype) :: a
   REAL(kind=realtype) :: scaledim, fact, factmoment
   REAL(kind=realtype) :: factb, factmomentb
   ! Functions
   REAL(kind=realtype), DIMENSION(ntimeintervalsspectral) :: dphix, dphiy&
   &  , dphiz
   REAL(kind=realtype), DIMENSION(ntimeintervalsspectral) :: dphixdot, &
   &  dphiydot, dphizdot
   REAL(kind=realtype) :: derivativerigidrotangle, &
   &  secondderivativerigidrotangle
   REAL(kind=realtype) :: TSALPHA, TSALPHADOT
   EXTERNAL TERMINATE
   REAL(kind=realtype) :: arg1
   REAL(kind=realtype) :: temp0
   REAL(kind=realtype) :: temp1b
   INTRINSIC SQRT
   REAL(kind=realtype) :: temp
   REAL*8 :: temp1b2(8)
   REAL(kind=realtype) :: temp1b1
   REAL(kind=realtype) :: temp1b0
   !
   !     ******************************************************************
   !     *                                                                *
   !     * Begin execution.                                               *
   !     *                                                                *
   !     ******************************************************************
   !
   scaledim = pref/pinf
   fact = two/(gammainf*pinf*machcoef**2*surfaceref*lref**2*scaledim)
   factmoment = fact/(lengthref*lref)
   IF (tsqmode) THEN
   STOP
   ! !q is pitch
   ! do sps =1,nTimeIntervalsSpectral
   !    !compute the time of this intervavc
   !    t = timeUnsteadyRestart
   !    if(equationMode == timeSpectral) then
   !       do nn=1,nSections
   !          t(nn) = t(nn) + (sps-1)*sections(nn)%timePeriod &
   !               /         (nTimeIntervalsSpectral*1.0)
   !       enddo
   !    endif
   !    ! Compute the time derivative of the rotation angles around the
   !    ! z-axis. i.e. compute q
   !    dphiZ(sps) = derivativeRigidRotAngle(degreePolZRot,   &
   !         coefPolZRot,     &
   !         degreeFourZRot,  &
   !         omegaFourZRot,   &
   !         cosCoefFourZRot, &
   !         sinCoefFourZRot, t)
   !    ! add in q_dot computation
   !    dphiZdot(sps) = secondDerivativeRigidRotAngle(degreePolZRot,   &
   !         coefPolZRot,     &
   !         degreeFourZRot,  &
   !         omegaFourZRot,   &
   !         cosCoefFourZRot, &
   !         sinCoefFourZRot, t)
   ! end do
   ! !now compute dCl/dq
   ! do i =1,8
   !    call computeLeastSquaresRegression(BaseCoef(:,i),dphiz,nTimeIntervalsSpectral,dcdq(i),coef0(i))
   ! end do
   ! ! now subtract off estimated cl,cmz and use remainder to compute 
   ! ! clqdot and cmzqdot.
   ! do i = 1,8
   !    do sps = 1,nTimeIntervalsSpectral
   !       ResBaseCoef(sps,i) = BaseCoef(sps,i)-(dcdq(i)*dphiz(sps)+Coef0(i))
   !    enddo
   ! enddo
   ! !now normalize the results...
   ! a  = sqrt(gammaInf*pInfDim/rhoInfDim)
   ! dcdq = dcdq*timeRef*2*(machGrid*a)/lengthRef
   ! !now compute dCl/dpdot
   ! do i = 1,8
   !    call computeLeastSquaresRegression(ResBaseCoef(:,i),dphizdot,nTimeIntervalsSpectral,dcdqdot(i),Coef0dot(i))
   ! enddo
   ELSE
   IF (tsalphamode) THEN
   DO sps=1,ntimeintervalsspectral
   !compute the time of this interval
   t = timeunsteadyrestart
   IF (equationmode .EQ. timespectral) THEN
   DO nn=1,nsections
   t(nn) = t(nn) + (sps-1)*sections(nn)%timeperiod/(&
   &              ntimeintervalsspectral*1.0)
   END DO
   END IF
   intervalalpha(sps) = TSALPHA(degreepolalpha, coefpolalpha, &
   &          degreefouralpha, omegafouralpha, coscoeffouralpha, &
   &          sincoeffouralpha, t)
   intervalalphadot(sps) = TSALPHADOT(degreepolalpha, &
   &          coefpolalpha, degreefouralpha, omegafouralpha, &
   &          coscoeffouralpha, sincoeffouralpha, t)
   basecoef(sps, 1) = fact*(force(1, sps)*liftdirection(1)+force(2&
   &          , sps)*liftdirection(2)+force(3, sps)*liftdirection(3))
   basecoef(sps, 2) = fact*(force(1, sps)*dragdirection(1)+force(2&
   &          , sps)*dragdirection(2)+force(3, sps)*dragdirection(3))
   basecoef(sps, 3) = force(1, sps)*fact
   basecoef(sps, 4) = force(2, sps)*fact
   basecoef(sps, 5) = force(3, sps)*fact
   basecoef(sps, 6) = moment(1, sps)*factmoment
   basecoef(sps, 7) = moment(2, sps)*factmoment
   basecoef(sps, 8) = moment(3, sps)*factmoment
   END DO
   !now compute dCl/dalpha
   DO i=1,8
   CALL COMPUTELEASTSQUARESREGRESSION(basecoef(:, i), &
   &                                        intervalalpha, &
   &                                        ntimeintervalsspectral, dcdalpha&
   &                                        (i), coef0(i))
   END DO
   ! now subtract off estimated cl,cmz and use remainder to compute 
   ! clalphadot and cmzalphadot.
   DO i=1,8
   DO sps=1,ntimeintervalsspectral
   resbasecoef(sps, i) = basecoef(sps, i) - (dcdalpha(i)*&
   &            intervalalpha(sps)+coef0(i))
   END DO
   END DO
   !now compute dCi/dalphadot
   DO i=1,8
   CALL COMPUTELEASTSQUARESREGRESSION(resbasecoef(:, i), &
   &                                        intervalalphadot, &
   &                                        ntimeintervalsspectral, &
   &                                        dcdalphadot(i), coef0dot(i))
   END DO
   a = SQRT(gammainf*pinfdim/rhoinfdim)
   temp1b2 = a*2*dcdalphadotb/lengthref
   machgridb = SUM(dcdalphadot*temp1b2)
   lengthrefb = lengthrefb + SUM(-(dcdalphadot*machgrid*temp1b2/&
   &        lengthref))
   dcdalphadotb = machgrid*temp1b2
   resbasecoefb = 0.0_8
   DO i=8,1,-1
   coef0dotb = 0.0_8
   CALL COMPUTELEASTSQUARESREGRESSION_B(resbasecoef(:, i), &
   &                                       resbasecoefb(:, i), &
   &                                       intervalalphadot, &
   &                                       ntimeintervalsspectral, &
   &                                       dcdalphadot(i), dcdalphadotb(i), &
   &                                       coef0dot(i), coef0dotb(i))
   dcdalphadotb(i) = 0.0_8
   coef0dotb(i) = 0.0_8
   END DO
   basecoefb = 0.0_8
   DO i=8,1,-1
   DO sps=ntimeintervalsspectral,1,-1
   basecoefb(sps, i) = basecoefb(sps, i) + resbasecoefb(sps, i)
   dcdalphab(i) = dcdalphab(i) - intervalalpha(sps)*resbasecoefb(&
   &            sps, i)
   coef0b(i) = coef0b(i) - resbasecoefb(sps, i)
   resbasecoefb(sps, i) = 0.0_8
   END DO
   END DO
   DO i=8,1,-1
   CALL COMPUTELEASTSQUARESREGRESSION_B(basecoef(:, i), basecoefb(:&
   &                                       , i), intervalalpha, &
   &                                       ntimeintervalsspectral, dcdalpha(&
   &                                       i), dcdalphab(i), coef0(i), &
   &                                       coef0b(i))
   dcdalphab(i) = 0.0_8
   coef0b(i) = 0.0_8
   END DO
   factmomentb = 0.0_8
   factb = 0.0_8
   DO sps=ntimeintervalsspectral,1,-1
   momentb(3, sps) = momentb(3, sps) + factmoment*basecoefb(sps, 8)
   factmomentb = factmomentb + moment(3, sps)*basecoefb(sps, 8)
   basecoefb(sps, 8) = 0.0_8
   momentb(2, sps) = momentb(2, sps) + factmoment*basecoefb(sps, 7)
   factmomentb = factmomentb + moment(2, sps)*basecoefb(sps, 7)
   basecoefb(sps, 7) = 0.0_8
   momentb(1, sps) = momentb(1, sps) + factmoment*basecoefb(sps, 6)
   factmomentb = factmomentb + moment(1, sps)*basecoefb(sps, 6)
   basecoefb(sps, 6) = 0.0_8
   forceb(3, sps) = forceb(3, sps) + fact*basecoefb(sps, 5)
   factb = factb + force(3, sps)*basecoefb(sps, 5)
   basecoefb(sps, 5) = 0.0_8
   forceb(2, sps) = forceb(2, sps) + fact*basecoefb(sps, 4)
   factb = factb + force(2, sps)*basecoefb(sps, 4)
   basecoefb(sps, 4) = 0.0_8
   forceb(1, sps) = forceb(1, sps) + fact*basecoefb(sps, 3)
   factb = factb + force(1, sps)*basecoefb(sps, 3)
   basecoefb(sps, 3) = 0.0_8
   temp1b0 = fact*basecoefb(sps, 2)
   factb = factb + (force(1, sps)*dragdirection(1)+force(2, sps)*&
   &          dragdirection(2)+force(3, sps)*dragdirection(3))*basecoefb(sps&
   &          , 2)
   forceb(1, sps) = forceb(1, sps) + dragdirection(1)*temp1b0
   dragdirectionb(1) = dragdirectionb(1) + force(1, sps)*temp1b0
   forceb(2, sps) = forceb(2, sps) + dragdirection(2)*temp1b0
   dragdirectionb(2) = dragdirectionb(2) + force(2, sps)*temp1b0
   forceb(3, sps) = forceb(3, sps) + dragdirection(3)*temp1b0
   dragdirectionb(3) = dragdirectionb(3) + force(3, sps)*temp1b0
   basecoefb(sps, 2) = 0.0_8
   temp1b1 = fact*basecoefb(sps, 1)
   factb = factb + (force(1, sps)*liftdirection(1)+force(2, sps)*&
   &          liftdirection(2)+force(3, sps)*liftdirection(3))*basecoefb(sps&
   &          , 1)
   forceb(1, sps) = forceb(1, sps) + liftdirection(1)*temp1b1
   liftdirectionb(1) = liftdirectionb(1) + force(1, sps)*temp1b1
   forceb(2, sps) = forceb(2, sps) + liftdirection(2)*temp1b1
   liftdirectionb(2) = liftdirectionb(2) + force(2, sps)*temp1b1
   forceb(3, sps) = forceb(3, sps) + liftdirection(3)*temp1b1
   liftdirectionb(3) = liftdirectionb(3) + force(3, sps)*temp1b1
   basecoefb(sps, 1) = 0.0_8
   END DO
   ELSE
   machgridb = 0.0_8
   factmomentb = 0.0_8
   factb = 0.0_8
   END IF
   temp1b = factmomentb/(lref*lengthref)
   factb = factb + temp1b
   lengthrefb = lengthrefb - fact*temp1b/lengthref
   temp0 = gammainf*pinf*lref**2*surfaceref*scaledim
   temp = temp0*machcoef**2
   machcoefb = -(temp0*two*2*machcoef*factb/temp**2)
   END IF
   END SUBROUTINE COMPUTETSDERIVATIVES_B
